version: '2'
services:
  dbms:
    build: ./dbms
    volumes:
      - config:/etc/postgresql
      - data:/var/lib/postgresql
      - log:/var/log/postgresql
    ports:
      - 5432:5432
volumes:
  config:
  data:
  log:
