version: "2"
services:
  apache:
    image: httpd
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./logs:/usr/local/apache2/logs
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"